#YAML
#
# Raw data
#
volatility_calculation:
   func: "syscore.algos.robust_vol_calc"
   days: 35
#
# Trading rules
#
trading_rules:
  ewmac8:
     function: systems.provided.example.rules.ewmac_forecast_with_defaults_no_vol
     data:
         - "rawdata.daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args: 
         Lfast: 8
         Lslow: 32
  ewmac16:
     function: systems.provided.example.rules.ewmac_forecast_with_defaults_no_vol
     data:
         - "rawdata.daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args: 
         Lfast: 16
         Lslow: 64
  carry:
     function: systems.provided.futures_chapter15.rules.carry
     data:
         - "rawdata.daily_annualised_roll"
         - "rawdata.daily_returns_volatility"
     other_args:
         smooth_days: 90
#
# forecast capping and scaling
#
forecast_cap: 21.0
#
forecast_scalar_estimate:
   pool_instruments: True
   func: "syscore.algos.forecast_scalar"
   window: 250000
   min_periods: 500
   backfill: True
#
# forecast combination
#
forecast_weights:
     ewmac8: 0.50
     ewmac16: 0.50
#
rule_variations:
     EDOLLAR: ['ewmac8','ewmac16', 'carry']
     US10: ['ewmac8','ewmac16', 'carry']
     BUND: ['ewmac8','ewmac16']
#
#
forecast_correlation_estimate:
   pool_instruments: True
   func: syscore.correlations.CorrelationEstimator
   frequency: "W"
   date_method: "expanding"
   using_exponent: True
   ew_lookback: 250
   min_periods: 20      
   cleaning: True
#
#
# Capital correction
#
percentage_vol_target: 16.0
notional_trading_capital: 100000
base_currency: "GBP"
#
# Portfolio creation
#
instrument_weights:
     EDOLLAR: 0.333
     US10: 0.333
     BUND: 0.333
instrument_div_multiplier: 1.2

