#YAML
parameters:
  vol_norm_return_limit: 6.0
  volatility_calculation:
    func: "syscore.algos.robust_vol_calc"
    days: 35
  smooth_rolldown_for_carry: 125
trading_rules:
  ewmac8:
     function: systems.provided.example.rules.ewmac_forecast_with_defaults_no_vol
     data:
         - "rawdata.daily_prices"
         - "rawdata.daily_returns_volatility"
     args: 
         Lfast: 8
         Lslow: 32

